/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthCallbackRouteImport } from './routes/auth.callback'
import { Route as AuthenticatedTopsRouteImport } from './routes/_authenticated/tops'
import { Route as AuthenticatedReceitasRouteImport } from './routes/_authenticated/receitas'
import { Route as AuthenticatedPremiosRouteImport } from './routes/_authenticated/premios'
import { Route as AuthenticatedPrecarioRouteImport } from './routes/_authenticated/precario'
import { Route as AuthenticatedOperacoesRouteImport } from './routes/_authenticated/operacoes'
import { Route as AuthenticatedOnboardingRouteImport } from './routes/_authenticated/onboarding'
import { Route as AuthenticatedNotificacoesRouteImport } from './routes/_authenticated/notificacoes'
import { Route as AuthenticatedMembrosRouteImport } from './routes/_authenticated/membros'
import { Route as AuthenticatedLiquidacaoRouteImport } from './routes/_authenticated/liquidacao'
import { Route as AuthenticatedInventarioRouteImport } from './routes/_authenticated/inventario'
import { Route as AuthenticatedEntregasRouteImport } from './routes/_authenticated/entregas'
import { Route as AuthenticatedEncomendasRouteImport } from './routes/_authenticated/encomendas'
import { Route as AuthenticatedDisponibilidadeRouteImport } from './routes/_authenticated/disponibilidade'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedAuditoriaRouteImport } from './routes/_authenticated/auditoria'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedOperacoesIndexRouteImport } from './routes/_authenticated/operacoes.index'
import { Route as AuthenticatedMembrosIndexRouteImport } from './routes/_authenticated/membros.index'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin.index'
import { Route as AuthenticatedOperacoesIdRouteImport } from './routes/_authenticated/operacoes.$id'
import { Route as AuthenticatedMembrosIdRouteImport } from './routes/_authenticated/membros.$id'
import { Route as AuthenticatedAdminReceitasRouteImport } from './routes/_authenticated/admin.receitas'
import { Route as AuthenticatedAdminPrecosRouteImport } from './routes/_authenticated/admin.precos'
import { Route as AuthenticatedAdminDashboardRouteImport } from './routes/_authenticated/admin.dashboard'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/auth/callback',
  path: '/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedTopsRoute = AuthenticatedTopsRouteImport.update({
  id: '/tops',
  path: '/tops',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedReceitasRoute = AuthenticatedReceitasRouteImport.update({
  id: '/receitas',
  path: '/receitas',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedPremiosRoute = AuthenticatedPremiosRouteImport.update({
  id: '/premios',
  path: '/premios',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedPrecarioRoute = AuthenticatedPrecarioRouteImport.update({
  id: '/precario',
  path: '/precario',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedOperacoesRoute = AuthenticatedOperacoesRouteImport.update({
  id: '/operacoes',
  path: '/operacoes',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedOnboardingRoute = AuthenticatedOnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedNotificacoesRoute =
  AuthenticatedNotificacoesRouteImport.update({
    id: '/notificacoes',
    path: '/notificacoes',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedMembrosRoute = AuthenticatedMembrosRouteImport.update({
  id: '/membros',
  path: '/membros',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedLiquidacaoRoute = AuthenticatedLiquidacaoRouteImport.update({
  id: '/liquidacao',
  path: '/liquidacao',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedInventarioRoute = AuthenticatedInventarioRouteImport.update({
  id: '/inventario',
  path: '/inventario',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedEntregasRoute = AuthenticatedEntregasRouteImport.update({
  id: '/entregas',
  path: '/entregas',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedEncomendasRoute = AuthenticatedEncomendasRouteImport.update({
  id: '/encomendas',
  path: '/encomendas',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDisponibilidadeRoute =
  AuthenticatedDisponibilidadeRouteImport.update({
    id: '/disponibilidade',
    path: '/disponibilidade',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAuditoriaRoute = AuthenticatedAuditoriaRouteImport.update({
  id: '/auditoria',
  path: '/auditoria',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedOperacoesIndexRoute =
  AuthenticatedOperacoesIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedOperacoesRoute,
  } as any)
const AuthenticatedMembrosIndexRoute =
  AuthenticatedMembrosIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedMembrosRoute,
  } as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedOperacoesIdRoute =
  AuthenticatedOperacoesIdRouteImport.update({
    id: '/$id',
    path: '/$id',
    getParentRoute: () => AuthenticatedOperacoesRoute,
  } as any)
const AuthenticatedMembrosIdRoute = AuthenticatedMembrosIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AuthenticatedMembrosRoute,
} as any)
const AuthenticatedAdminReceitasRoute =
  AuthenticatedAdminReceitasRouteImport.update({
    id: '/receitas',
    path: '/receitas',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminPrecosRoute =
  AuthenticatedAdminPrecosRouteImport.update({
    id: '/precos',
    path: '/precos',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminDashboardRoute =
  AuthenticatedAdminDashboardRouteImport.update({
    id: '/dashboard',
    path: '/dashboard',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/admin': typeof AuthenticatedAdminRouteWithChildren
  '/auditoria': typeof AuthenticatedAuditoriaRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/disponibilidade': typeof AuthenticatedDisponibilidadeRoute
  '/encomendas': typeof AuthenticatedEncomendasRoute
  '/entregas': typeof AuthenticatedEntregasRoute
  '/inventario': typeof AuthenticatedInventarioRoute
  '/liquidacao': typeof AuthenticatedLiquidacaoRoute
  '/membros': typeof AuthenticatedMembrosRouteWithChildren
  '/notificacoes': typeof AuthenticatedNotificacoesRoute
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/operacoes': typeof AuthenticatedOperacoesRouteWithChildren
  '/precario': typeof AuthenticatedPrecarioRoute
  '/premios': typeof AuthenticatedPremiosRoute
  '/receitas': typeof AuthenticatedReceitasRoute
  '/tops': typeof AuthenticatedTopsRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/admin/dashboard': typeof AuthenticatedAdminDashboardRoute
  '/admin/precos': typeof AuthenticatedAdminPrecosRoute
  '/admin/receitas': typeof AuthenticatedAdminReceitasRoute
  '/membros/$id': typeof AuthenticatedMembrosIdRoute
  '/operacoes/$id': typeof AuthenticatedOperacoesIdRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
  '/membros/': typeof AuthenticatedMembrosIndexRoute
  '/operacoes/': typeof AuthenticatedOperacoesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/auditoria': typeof AuthenticatedAuditoriaRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/disponibilidade': typeof AuthenticatedDisponibilidadeRoute
  '/encomendas': typeof AuthenticatedEncomendasRoute
  '/entregas': typeof AuthenticatedEntregasRoute
  '/inventario': typeof AuthenticatedInventarioRoute
  '/liquidacao': typeof AuthenticatedLiquidacaoRoute
  '/notificacoes': typeof AuthenticatedNotificacoesRoute
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/precario': typeof AuthenticatedPrecarioRoute
  '/premios': typeof AuthenticatedPremiosRoute
  '/receitas': typeof AuthenticatedReceitasRoute
  '/tops': typeof AuthenticatedTopsRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/admin/dashboard': typeof AuthenticatedAdminDashboardRoute
  '/admin/precos': typeof AuthenticatedAdminPrecosRoute
  '/admin/receitas': typeof AuthenticatedAdminReceitasRoute
  '/membros/$id': typeof AuthenticatedMembrosIdRoute
  '/operacoes/$id': typeof AuthenticatedOperacoesIdRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
  '/membros': typeof AuthenticatedMembrosIndexRoute
  '/operacoes': typeof AuthenticatedOperacoesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRouteWithChildren
  '/_authenticated/auditoria': typeof AuthenticatedAuditoriaRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/disponibilidade': typeof AuthenticatedDisponibilidadeRoute
  '/_authenticated/encomendas': typeof AuthenticatedEncomendasRoute
  '/_authenticated/entregas': typeof AuthenticatedEntregasRoute
  '/_authenticated/inventario': typeof AuthenticatedInventarioRoute
  '/_authenticated/liquidacao': typeof AuthenticatedLiquidacaoRoute
  '/_authenticated/membros': typeof AuthenticatedMembrosRouteWithChildren
  '/_authenticated/notificacoes': typeof AuthenticatedNotificacoesRoute
  '/_authenticated/onboarding': typeof AuthenticatedOnboardingRoute
  '/_authenticated/operacoes': typeof AuthenticatedOperacoesRouteWithChildren
  '/_authenticated/precario': typeof AuthenticatedPrecarioRoute
  '/_authenticated/premios': typeof AuthenticatedPremiosRoute
  '/_authenticated/receitas': typeof AuthenticatedReceitasRoute
  '/_authenticated/tops': typeof AuthenticatedTopsRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/_authenticated/admin/dashboard': typeof AuthenticatedAdminDashboardRoute
  '/_authenticated/admin/precos': typeof AuthenticatedAdminPrecosRoute
  '/_authenticated/admin/receitas': typeof AuthenticatedAdminReceitasRoute
  '/_authenticated/membros/$id': typeof AuthenticatedMembrosIdRoute
  '/_authenticated/operacoes/$id': typeof AuthenticatedOperacoesIdRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
  '/_authenticated/membros/': typeof AuthenticatedMembrosIndexRoute
  '/_authenticated/operacoes/': typeof AuthenticatedOperacoesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/admin'
    | '/auditoria'
    | '/dashboard'
    | '/disponibilidade'
    | '/encomendas'
    | '/entregas'
    | '/inventario'
    | '/liquidacao'
    | '/membros'
    | '/notificacoes'
    | '/onboarding'
    | '/operacoes'
    | '/precario'
    | '/premios'
    | '/receitas'
    | '/tops'
    | '/auth/callback'
    | '/admin/dashboard'
    | '/admin/precos'
    | '/admin/receitas'
    | '/membros/$id'
    | '/operacoes/$id'
    | '/admin/'
    | '/membros/'
    | '/operacoes/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/auditoria'
    | '/dashboard'
    | '/disponibilidade'
    | '/encomendas'
    | '/entregas'
    | '/inventario'
    | '/liquidacao'
    | '/notificacoes'
    | '/onboarding'
    | '/precario'
    | '/premios'
    | '/receitas'
    | '/tops'
    | '/auth/callback'
    | '/admin/dashboard'
    | '/admin/precos'
    | '/admin/receitas'
    | '/membros/$id'
    | '/operacoes/$id'
    | '/admin'
    | '/membros'
    | '/operacoes'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/login'
    | '/_authenticated/admin'
    | '/_authenticated/auditoria'
    | '/_authenticated/dashboard'
    | '/_authenticated/disponibilidade'
    | '/_authenticated/encomendas'
    | '/_authenticated/entregas'
    | '/_authenticated/inventario'
    | '/_authenticated/liquidacao'
    | '/_authenticated/membros'
    | '/_authenticated/notificacoes'
    | '/_authenticated/onboarding'
    | '/_authenticated/operacoes'
    | '/_authenticated/precario'
    | '/_authenticated/premios'
    | '/_authenticated/receitas'
    | '/_authenticated/tops'
    | '/auth/callback'
    | '/_authenticated/admin/dashboard'
    | '/_authenticated/admin/precos'
    | '/_authenticated/admin/receitas'
    | '/_authenticated/membros/$id'
    | '/_authenticated/operacoes/$id'
    | '/_authenticated/admin/'
    | '/_authenticated/membros/'
    | '/_authenticated/operacoes/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginRoute: typeof LoginRoute
  AuthCallbackRoute: typeof AuthCallbackRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/auth/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/tops': {
      id: '/_authenticated/tops'
      path: '/tops'
      fullPath: '/tops'
      preLoaderRoute: typeof AuthenticatedTopsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/receitas': {
      id: '/_authenticated/receitas'
      path: '/receitas'
      fullPath: '/receitas'
      preLoaderRoute: typeof AuthenticatedReceitasRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/premios': {
      id: '/_authenticated/premios'
      path: '/premios'
      fullPath: '/premios'
      preLoaderRoute: typeof AuthenticatedPremiosRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/precario': {
      id: '/_authenticated/precario'
      path: '/precario'
      fullPath: '/precario'
      preLoaderRoute: typeof AuthenticatedPrecarioRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/operacoes': {
      id: '/_authenticated/operacoes'
      path: '/operacoes'
      fullPath: '/operacoes'
      preLoaderRoute: typeof AuthenticatedOperacoesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/onboarding': {
      id: '/_authenticated/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof AuthenticatedOnboardingRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/notificacoes': {
      id: '/_authenticated/notificacoes'
      path: '/notificacoes'
      fullPath: '/notificacoes'
      preLoaderRoute: typeof AuthenticatedNotificacoesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/membros': {
      id: '/_authenticated/membros'
      path: '/membros'
      fullPath: '/membros'
      preLoaderRoute: typeof AuthenticatedMembrosRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/liquidacao': {
      id: '/_authenticated/liquidacao'
      path: '/liquidacao'
      fullPath: '/liquidacao'
      preLoaderRoute: typeof AuthenticatedLiquidacaoRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/inventario': {
      id: '/_authenticated/inventario'
      path: '/inventario'
      fullPath: '/inventario'
      preLoaderRoute: typeof AuthenticatedInventarioRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/entregas': {
      id: '/_authenticated/entregas'
      path: '/entregas'
      fullPath: '/entregas'
      preLoaderRoute: typeof AuthenticatedEntregasRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/encomendas': {
      id: '/_authenticated/encomendas'
      path: '/encomendas'
      fullPath: '/encomendas'
      preLoaderRoute: typeof AuthenticatedEncomendasRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/disponibilidade': {
      id: '/_authenticated/disponibilidade'
      path: '/disponibilidade'
      fullPath: '/disponibilidade'
      preLoaderRoute: typeof AuthenticatedDisponibilidadeRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/auditoria': {
      id: '/_authenticated/auditoria'
      path: '/auditoria'
      fullPath: '/auditoria'
      preLoaderRoute: typeof AuthenticatedAuditoriaRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/operacoes/': {
      id: '/_authenticated/operacoes/'
      path: '/'
      fullPath: '/operacoes/'
      preLoaderRoute: typeof AuthenticatedOperacoesIndexRouteImport
      parentRoute: typeof AuthenticatedOperacoesRoute
    }
    '/_authenticated/membros/': {
      id: '/_authenticated/membros/'
      path: '/'
      fullPath: '/membros/'
      preLoaderRoute: typeof AuthenticatedMembrosIndexRouteImport
      parentRoute: typeof AuthenticatedMembrosRoute
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/operacoes/$id': {
      id: '/_authenticated/operacoes/$id'
      path: '/$id'
      fullPath: '/operacoes/$id'
      preLoaderRoute: typeof AuthenticatedOperacoesIdRouteImport
      parentRoute: typeof AuthenticatedOperacoesRoute
    }
    '/_authenticated/membros/$id': {
      id: '/_authenticated/membros/$id'
      path: '/$id'
      fullPath: '/membros/$id'
      preLoaderRoute: typeof AuthenticatedMembrosIdRouteImport
      parentRoute: typeof AuthenticatedMembrosRoute
    }
    '/_authenticated/admin/receitas': {
      id: '/_authenticated/admin/receitas'
      path: '/receitas'
      fullPath: '/admin/receitas'
      preLoaderRoute: typeof AuthenticatedAdminReceitasRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/precos': {
      id: '/_authenticated/admin/precos'
      path: '/precos'
      fullPath: '/admin/precos'
      preLoaderRoute: typeof AuthenticatedAdminPrecosRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/dashboard': {
      id: '/_authenticated/admin/dashboard'
      path: '/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof AuthenticatedAdminDashboardRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
  }
}

interface AuthenticatedAdminRouteChildren {
  AuthenticatedAdminDashboardRoute: typeof AuthenticatedAdminDashboardRoute
  AuthenticatedAdminPrecosRoute: typeof AuthenticatedAdminPrecosRoute
  AuthenticatedAdminReceitasRoute: typeof AuthenticatedAdminReceitasRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
}

const AuthenticatedAdminRouteChildren: AuthenticatedAdminRouteChildren = {
  AuthenticatedAdminDashboardRoute: AuthenticatedAdminDashboardRoute,
  AuthenticatedAdminPrecosRoute: AuthenticatedAdminPrecosRoute,
  AuthenticatedAdminReceitasRoute: AuthenticatedAdminReceitasRoute,
  AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
}

const AuthenticatedAdminRouteWithChildren =
  AuthenticatedAdminRoute._addFileChildren(AuthenticatedAdminRouteChildren)

interface AuthenticatedMembrosRouteChildren {
  AuthenticatedMembrosIdRoute: typeof AuthenticatedMembrosIdRoute
  AuthenticatedMembrosIndexRoute: typeof AuthenticatedMembrosIndexRoute
}

const AuthenticatedMembrosRouteChildren: AuthenticatedMembrosRouteChildren = {
  AuthenticatedMembrosIdRoute: AuthenticatedMembrosIdRoute,
  AuthenticatedMembrosIndexRoute: AuthenticatedMembrosIndexRoute,
}

const AuthenticatedMembrosRouteWithChildren =
  AuthenticatedMembrosRoute._addFileChildren(AuthenticatedMembrosRouteChildren)

interface AuthenticatedOperacoesRouteChildren {
  AuthenticatedOperacoesIdRoute: typeof AuthenticatedOperacoesIdRoute
  AuthenticatedOperacoesIndexRoute: typeof AuthenticatedOperacoesIndexRoute
}

const AuthenticatedOperacoesRouteChildren: AuthenticatedOperacoesRouteChildren =
  {
    AuthenticatedOperacoesIdRoute: AuthenticatedOperacoesIdRoute,
    AuthenticatedOperacoesIndexRoute: AuthenticatedOperacoesIndexRoute,
  }

const AuthenticatedOperacoesRouteWithChildren =
  AuthenticatedOperacoesRoute._addFileChildren(
    AuthenticatedOperacoesRouteChildren,
  )

interface AuthenticatedRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRouteWithChildren
  AuthenticatedAuditoriaRoute: typeof AuthenticatedAuditoriaRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedDisponibilidadeRoute: typeof AuthenticatedDisponibilidadeRoute
  AuthenticatedEncomendasRoute: typeof AuthenticatedEncomendasRoute
  AuthenticatedEntregasRoute: typeof AuthenticatedEntregasRoute
  AuthenticatedInventarioRoute: typeof AuthenticatedInventarioRoute
  AuthenticatedLiquidacaoRoute: typeof AuthenticatedLiquidacaoRoute
  AuthenticatedMembrosRoute: typeof AuthenticatedMembrosRouteWithChildren
  AuthenticatedNotificacoesRoute: typeof AuthenticatedNotificacoesRoute
  AuthenticatedOnboardingRoute: typeof AuthenticatedOnboardingRoute
  AuthenticatedOperacoesRoute: typeof AuthenticatedOperacoesRouteWithChildren
  AuthenticatedPrecarioRoute: typeof AuthenticatedPrecarioRoute
  AuthenticatedPremiosRoute: typeof AuthenticatedPremiosRoute
  AuthenticatedReceitasRoute: typeof AuthenticatedReceitasRoute
  AuthenticatedTopsRoute: typeof AuthenticatedTopsRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRouteWithChildren,
  AuthenticatedAuditoriaRoute: AuthenticatedAuditoriaRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedDisponibilidadeRoute: AuthenticatedDisponibilidadeRoute,
  AuthenticatedEncomendasRoute: AuthenticatedEncomendasRoute,
  AuthenticatedEntregasRoute: AuthenticatedEntregasRoute,
  AuthenticatedInventarioRoute: AuthenticatedInventarioRoute,
  AuthenticatedLiquidacaoRoute: AuthenticatedLiquidacaoRoute,
  AuthenticatedMembrosRoute: AuthenticatedMembrosRouteWithChildren,
  AuthenticatedNotificacoesRoute: AuthenticatedNotificacoesRoute,
  AuthenticatedOnboardingRoute: AuthenticatedOnboardingRoute,
  AuthenticatedOperacoesRoute: AuthenticatedOperacoesRouteWithChildren,
  AuthenticatedPrecarioRoute: AuthenticatedPrecarioRoute,
  AuthenticatedPremiosRoute: AuthenticatedPremiosRoute,
  AuthenticatedReceitasRoute: AuthenticatedReceitasRoute,
  AuthenticatedTopsRoute: AuthenticatedTopsRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
  AuthCallbackRoute: AuthCallbackRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
